### ISSUE TITLE
share-before markup duplicated

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-share#35]
The markup and script for the before content selection are duplicated in the source code, which doesn't validate.

```html
<div class="share-before share-filled share-small" id="share-before-1222">
<div class="googlePlus" id="googleplus-before-1222" data-url="http://site.com/podcast/test-podcast/" data-urlalt="http://site.com/?p=1222" data-text="test podcast" data-title="Share"></div>
<div class="facebook" id="facebook-before-1222" data-url="http://site.com/podcast/test-podcast/" data-urlalt="http://site.com/?p=1222" data-text="test podcast" data-title="Share"></div>
<div class="pinterest" id="pinterest-before-1222" data-url="http://site.com/podcast/test-podcast/" data-urlalt="http://site.com/?p=1222" data-text="test podcast" data-title="Pin"></div>
<div class="linkedin" id="linkedin-before-1222" data-url="http://site.com/podcast/test-podcast/" data-urlalt="http://site.com/?p=1222" data-text="test podcast" data-title="Share"></div>
</div>
```

**Comment by katyfb13** [comment]
@NicktheGeek please add some testing instructions on this

**Comment by NicktheGeek** [comment]
you will need to do the tests with various content options. Specifically you need to set the content archives for full content, full content + limit to X characters, and the excerpt.

In each scenario
- [ ] check to make sure share icons show above, below, and above and below the content in the archives
- [ ] check to make sure share icons show above, below, and above and below the content in the single post/page/...
- [ ] check to make sure the markup doesn't include duplicate IDs

**Comment by katyfb13** [comment]
this looks good to me now. And I am not seeing the duplicate IDs but @dreamwhisper will you please double check my work?

**Comment by katyfb13** [comment]
marked this as needs dev since it seems the fix is not there yet
cc: @rrennick @NicktheGeek @dreamwhisper

**Comment by NicktheGeek** [comment]
changed it back. The fix was merged in and is showing in cbmpackage. Will be in the hourlies after the next update.

**Comment by katyfb13** [comment]
@dreamwhisper looks like the errors are gone now, but please confirm

**Comment by dreamwhisper** [comment]
Confirmed

**Comment by katyfb13** [comment]
wooo hoooo!

**Comment by r-diamond** [comment]
Confirmed and Production Ready
