### ISSUE TITLE
Warnings when saving a post with debug enabled.

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-share#36]
When updating a post with GSS only enabled, I'm seeing the following warnings:
`Notice: Undefined offset: 0 in /wp-includes/capabilities.php on line 1116`

`Warning: Cannot modify header information - headers already sent by (output started at /wp-includes/capabilities.php:1116) in /wp-admin/post.php on line 233`

`Warning: Cannot modify header information - headers already sent by (output started at /wp-includes/capabilities.php:1116) in /wp-includes/pluggable.php on line 1173`

**Comment by katyfb13** [comment]
I checked cbmpackage01 and don't see these errors. @dreamwhisper do you have a way to check this?

**Comment by dreamwhisper** [comment]
@katyfb13 I don't have a way to check on RM, but I initially reported it based on having Debug enabled on my WP dev site. I can confirm that I no longer get those errors.

**Comment by katyfb13** [comment]
okay thanks @dreamwhisper. Looks like debug is on on cbmpackage and I didn't see the errors there. So we'll just pass this along.
