### ISSUE TITLE
Adds # to end of URL

### ISSUE THREAD

**Issue by bgardner** [copyblogger/genesis-simple-share#37]
Not sure if this has been addressed or reported here already, but this seems to be an issue:

"Any plans on fixing the issue when you click to share it adds an “#” on the end of your URLs?"

**Comment by katyfb13** [comment]
@NicktheGeek this is in RM 2.2 but looks like it needs to move to 2.3?

**Comment by NicktheGeek** [comment]
yeah go with 2.3 for now

**Comment by katyfb13** [comment]
ok moved it. Thanks.

**Comment by karenskeen** [comment]
Fixing the issue when you click to share it adds an “#” on the end of URLs - would be great. 

Thanks.

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)

**Comment by dreamwhisper** [comment]
confirmed x3
