### ISSUE TITLE
Share After Duplication

### ISSUE THREAD

**Issue by TygrScott** [copyblogger/genesis-simple-share#40]
I haven't added any enhancements to the Simple Share plugin in my functions.php.
**Edit:** Removed mentions of multisite, turned out to not be the issue and irrelevant.

On pages or posts, if I use "After Content" I get
```
<div id="share-after-179" class="share-after share-filled share-medium"> (All code for buttons after)
<script type="text/javascript"> (jQuery script for G+, Facebook etc)
<div id="share-after-179" class="share-after share-filled share-medium"> (All code for buttons after)
<script type="text/javascript"> (jQuery script for G+, Facebook etc)
```

If I use Before Content, no issues. If I use Before and After Content, I get duplication at the bottom.

![sharethis](https://cloud.githubusercontent.com/assets/9156209/5335760/ffc153a0-7e6d-11e4-8acf-834483d91323.png)

**Comment by NicktheGeek** [comment]
@TygrScott Can you test this with the latest update. We fixed something similar to this already so I'm thinking you may have an outdated version.

**Comment by NicktheGeek** [comment]
#35 is where it was fixed. Looks like you tested that and it resolved this so closing as duplicate.
