### ISSUE TITLE
Google+ share counts no longer update

### ISSUE THREAD

**Issue by nutsandbolts** [copyblogger/genesis-simple-share#51]
On both self-hosted WP sites and RM sites, the G+ share count no longer appears to update correctly.

(1) Click the G+ button - the count will update immediately.
(2) Complete the share and refresh the page - the count will reset back to its previous value. This happens with or without caching and persists even several days after the content was shared.

This seems to be separate from any cURL issues on the server side that might prevent share counts from updating.

**Comment by NicktheGeek** [comment]
This may be an issue with servers blocking access to the php file that is used to get the G+ scripts. I've checked this in several sites/servers and it seems to be working in most cases. When we include an option to disable the count in general it will resolve this for servers where the php script is being blocked. Alternately the server setup could be changed to allow access to the script.
