### ISSUE TITLE
enqueue waypoints on front-page - AgencyPro

### ISSUE THREAD

**Issue by neilgee** [copyblogger/genesis-simple-share#53]
Was getting a JS error on front page for Agency Pro
`Uncaught TypeError: $(...).waypoint is not a function`

Have to enqueue waypoints in front-page.php to fix
`wp_enqueue_script( 'genesis-simple-share-waypoint-js' );`

**Comment by neilgee** [comment]
Actually the error will occur on anytheme's front page when you start to add posts into it using something like featured posts widget

**Comment by dreamwhisper** [comment]
This is a duplicate of https://github.com/copyblogger/genesis-simple-share/issues/49 so will close.
