### ISSUE TITLE
Include Alternate URL for sharing

### ISSUE THREAD

**Issue by NicktheGeek** [copyblogger/genesis-simple-share#54]
When moving URLs for various reasons one unexpected cost is loss of social proof. This means that if a page is a child of another page, you cannot move it to a different parent or remove the parent without starting over with social shares. You are also stuck if you switch post types or do anything else that changes the original URL.

If we include an alternate URL it should be possible to get around this by setting up the content under the new URL and redirecting the old URL to the new URL. This allows the old URL to be included as the alternate URL and all social shares to that old URL will show up. The visits to the alternate URL will be redirected to the new URL, so it is safe to continue sharing that URL going forward which keeps the social proof on the same URL.

This will also make it possible to use a shortcode to share specific URLs and some other functionality that has been requested.

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)

**Comment by nickcernis** [comment]
Confirmed.

<img width="1170" alt="share_a_link_on_twitter_and_edit_post_ _wp_test_ _wordpress_and_hello_world_" src="https://user-images.githubusercontent.com/647669/30719949-91b0cf2a-9f1d-11e7-9218-9af4ff73645f.png">
