### ISSUE TITLE
Use alt text for Pinterest description instead of post title

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#55]
The official Pinterest “Pin It” button ([Chrome](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&cad=rja&uact=8&ved=0CDoQFjAEahUKEwiR2-CXot_GAhUBL9sKHUypDkw&url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fpin-it-button%2Fgpdjojdkbbmdfjfahjcgigfpmkopogic%3Fhl%3Den&ei=4m-nVZHiF4He7AbM0rrgBA&usg=AFQjCNEfq6uPFF8qsTBlbB36lTMscDKv_Q&bvm=bv.97949915,d.ZGU)) pulls the Pinterest description from image alt text:

![post_in_category_13_-_test_site](https://cloud.githubusercontent.com/assets/647669/8719032/9533cbcc-2ba0-11e5-9f0b-e1cde4b8a695.jpg)

Genesis Simple Share currently uses the post title for the Pinterest description instead:

![pinterest__discover_and_save_creative_ideas_and_post_in_category_13_-_test_site](https://cloud.githubusercontent.com/assets/647669/8718997/625fe870-2ba0-11e5-8111-1a5e19cff337.jpg)

The post I'm testing this with is at http://nick-cernis.preview76.rmkr.net/post-category-13/.

User expectation is that the Pinterest description should come from image alt text if it's set, rather than from the post title.

Using alt text for the title is also recommended in [this post from the Copyblogger blog](http://www.copyblogger.com/get-more-from-pinterest/):

> When you upload images and embed them in your online content, pay special attention to the “Alt Text” for each image. Pinterest automatically reads “Alt” data when a Pinterest user pins your image — so whatever you enter as the “Alt Text” for a particular image becomes the default pin description for that image.

> Pinterest’s Guided Search looks at pin descriptions to decide which pins are relevant (and which are not) to show in user searches, so it’s critical to make the “Alt text” for every image keyword rich.

Perhaps Simple Share should also use alt text when available when sharing via Pinterest, just as the official Pinterest button does, then fall back on the post title if no alt text is available?

**Comment by NicktheGeek** [comment]
The share on pinterest button is effectively sharing the post and using the featured image. There isn't really alt text to pull from in the featured image. The script isn't scanning the page to find an image and share that. There are other plugins for pinning images which would be more appropriate to that usage.

**Comment by nickcernis** [comment]
> There isn't really alt text to pull from in the featured image.

I think something like this might work:

~~~php
$thumb_id = get_post_thumbnail_id( $post->ID );
$alt_text = get_post_meta( $thumb_id, '_wp_attachment_image_alt', true );
~~~

If no alt text is set for the image, `$alt_text` will be empty.

I agree with you that reproducing the entire functionality of the official Pinterest button to scan the page for images with JS might be overkill. I just wanted to report that customers find the existing GSS Pinterest share behaviour frustrating, because they're used to other Pinterest share buttons pulling in the alt text instead of the title. Right now, they have no way to set a custom description other than editing the title.

Other (non-official) implementations of share buttons automate the use of alt text by linking to `pin/find/` instead of `pin/create/`, which seems to give a sharing experience that's closer to the native Pinterest one.

e.g. Try clicking the Pinterest badge in [this article](http://www.theguardian.com/technology/2015/jul/16/pebble-boss-eric-migicovsky-smartwatches-app):

Is that worth considering as a workaround?

![pinterest-share](https://cloud.githubusercontent.com/assets/647669/8723116/2815aa10-2bc3-11e5-8ee8-5ce77bd90206.gif)
