### ISSUE TITLE
Use on non-Genesis theme

### ISSUE THREAD

**Issue by bradley2083** [copyblogger/genesis-simple-share#56]
Hey, guys. 

My client is moving away from a Genesis theme for a few different reasons and they have a TON of social share counts using the Simple Share plugin.  Is there a solution to keeping these stats in tact when using a non-Genesis Wordpress theme?  

Thank you!

**Comment by bgardner** [comment]
The plugin itself doesn't store the counts. All it does is connect via each social media service API and output the counts that are reported. In other words leaving the plugin won't lose any share count.

**Comment by bradley2083** [comment]
Nice, so it's just a matter of adding different share counts from various sources and I assume it's all based on the permalink then, right?

**Comment by bgardner** [comment]
Correct.

**Comment by bradley2083** [comment]
Great, thanks!
