### ISSUE TITLE
Need option to disable share count display

### ISSUE THREAD

**Issue by NicktheGeek** [copyblogger/genesis-simple-share#8]
Some users may not want to display the share count, especially if the count is particularly low. Also, there are times where the sharrre.php file used to get the count in Google+ and Stumble Upon can result in those buttons not loading at all.
see: https://github.com/copyblogger/genesis-simple-share/issues/6

**Comment by G-Madhavan** [comment]
I'd also like to add my request to have the option of removing the share count in this fine plugin.

**Comment by eslucky** [comment]
I third it!

**Comment by nickcernis** [comment]
Just noting that this request is becoming quite popular now. https://wordpress.org/support/topic/how-to-remove-the-count-from-all-buttons?replies=5#post-7533792

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)
