### ISSUE TITLE
mobile twitter styling

### ISSUE THREAD

**Issue by bellovia** [copyblogger/genesis-simple-share#82]
I'm using the plugin on a recent site re-design built on the altitude child theme and the tweet link seems to be expanded on mobile versions (480 px or narrower). Not sure if it's a plugin issue or a conflict with either the theme or another plugin that we're using. Hoping someone could take a peek and let me know if there's an adjustment I need to make in my theme to hide the "tweet" text. 

Link to example post: [http://kimklassen.com/welcome-to-our-new-home/](http://kimklassen.com/welcome-to-our-new-home/)

Thanks in advance! And thanks for the great plugin. 

![mobile_responsive_design_testing_-_2016-08-24_11 43 50](https://cloud.githubusercontent.com/assets/7872045/17937487/428f4844-69f0-11e6-91fa-324472ca177b.png)

**Comment by NicktheGeek** [comment]
@bellovia looks like this is custom CSS. I tried checking quickly to see if I can identify why it is doing this. Looks like you can add this to your style.css file to resolve
```
.share-small .no-count .share {
	width: 0;
}
```

**Comment by bellovia** [comment]
That worked. Thanks so much Nick!
