### ISSUE TITLE
Simple Share Tweet Button not showing correctly

### ISSUE THREAD

**Issue by btdsteph** [copyblogger/genesis-simple-share#87]
I am new to Wordpress and recently finished my site. But, on the simple share feature the tweet button is not showing correctly. I contacted the template designer but she said it's not on her end to contact the button designer. I've attached a file showing what it looks like on my site. Can you assist in getting it to show correctly. Thanks!
![button](https://cloud.githubusercontent.com/assets/25253090/22161110/e9e7c440-df16-11e6-996f-2dde73e2b080.jpg)

**Comment by NicktheGeek** [comment]
I could be wrong but I suspect this is not from this plugin. If it is, then it has some custom CSS and custom "SHARE IT" copy as it doesn't typically show like that. If you are certain it is this plugin then please provide a link to the site. We might be able to help identify where the errant CSS is coming from.
