### ISSUE TITLE
Author change to StudioPress

### ISSUE THREAD

**Issue by jaygidwitz** [copyblogger/genesis-simple-share#88]
The author for this plugin should change from `Rainmaker Digital LLC` to `StudioPress`. The URI will need to change as well.

<img width="781" alt="screenshot 2017-03-09 10 53 31" src="https://cloud.githubusercontent.com/assets/3248407/23765639/aaf39c1c-04b6-11e7-888b-539ef12bdcbf.png">

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)

**Comment by dreamwhisper** [comment]
Confirmed x3

**Comment by dreamwhisper** [comment]
@NicktheGeek - The author is right, but the link is wrong lol

https://github.com/copyblogger/genesis-simple-share/blob/develop/plugin.php#L11

**Comment by NicktheGeek** [comment]
updated

**Comment by nickcernis** [comment]
Confirmed.

**Comment by susannelson** [comment]
I just downloaded the latest version from https://github.com/copyblogger/genesis-simple-share and still see Rainmaker Digital, LLC as the author. Also, the link points to www.copyblogger.com instead of www.studiopress.com.

![image](https://user-images.githubusercontent.com/3220438/31135346-b9ab525c-a832-11e7-921f-97a0d456764d.png)

**Comment by dreamwhisper** [comment]
@susannelson I'm 99% sure that the changes haven't been merged to develop or master from the release/1.1 branch

**Comment by NicktheGeek** [comment]
@susannelson you will need to download from the branch to see these changes.

https://github.com/copyblogger/genesis-simple-share/tree/release/1.1

**Comment by susannelson** [comment]
Sorry. That gets me every time! I'm good to go now. :)
