### ISSUE TITLE
Google+ Counts not showing correctly

### ISSUE THREAD

**Issue by MissAmeliaSmith** [copyblogger/genesis-simple-share#91]
We have seen a few reports of the Google+ share button not showing share counts in both Rainmaker and from WordPress folks using the Genesis Simple Shares plugin. 

Google+ announced in June it would be removing the share counts from the Google+ share button and it looks like this has since happened.

**Related Articles**
Social Warfare article: https://warfareplugins.com/google-plus-share-counts/
Google Announcement: https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo

**Comment by NicktheGeek** [comment]
@rafaltomal is there anything different you'd recommend style wise for the button?

**Comment by bgardner** [comment]
Gonna be time, soon, to sunset this plugin. :-P

**Comment by bgardner** [comment]
^ That was a joke.

**Comment by rafaltomal** [comment]
@NicktheGeek looks like we have the same thing with the Twitter counter.

And this is what we did:

![image](https://user-images.githubusercontent.com/4073247/29539426-6bc7e2a4-868f-11e7-954b-c32726eff049.png)

**Comment by NicktheGeek** [comment]
@rafaltomal that is what I figured, just wanted to see if you wanted to approach it differently now that g+ and twitter are affected.

**Comment by NicktheGeek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Simple Share](https://trello.com/c/p4ZJkg29/10-genesis-simple-share)

**Comment by dreamwhisper** [comment]
Confirmed x3
