### ISSUE TITLE
Scripts missing in 1.1.0 version deployed to WP.org

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-share#93]
Minified JS files appear to be missing from 1.1.0:

https://wordpress.org/support/topic/error-last-update-2/

<img width="814" alt="ww7bhs" src="https://user-images.githubusercontent.com/647669/32254433-a688b558-be98-11e7-957c-529cd33677bf.png">

These files are missing:

<img width="216" alt="zjj2cb" src="https://user-images.githubusercontent.com/647669/32254642-03a57144-be9a-11e7-924d-67727931f08f.png">

Please could we bump the version and re-release with all JS and CSS files in place? They're generated via `npm install` and then `gulp build`. cc @nathanrice @mattlawck

**Comment by nathanrice** [comment]
https://wordpress.org/plugins/genesis-simple-share/
